version: "3"

services:
  app:
    build: .
    image: madeline
    container_name: madeline-app
    command: gunicorn --bind 0.0.0.0:5000 --workers 8 server:app
    ports:
      - "5000:5000"
    environment:
      - APP=madeline-app

  client:
    image: madeline
    container_name: madeline-client
    command: tail -f /dev/null
    links:
      - app
    environment:
      - APP=madeline-client
    depends_on:
      - app
